#!/bin/bash

# build dockerfile
echo "=> building containers" > /dev/stderr
dev/build


# bring up mysql container
docker-compose -f dev/docker-compose.yaml up -d mysql

# wait for mysql container to come up
wait_for "docker-compose -f dev/docker-compose.yaml exec mysql mysql -uroot -ppassword ecomm -e 'SELECT 1;'"
